spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/taskmanagerdb}
server.port=${PORT:8080}

# JWT settings
app.jwt.secret=ChangeThisSecretForProd
app.jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework=INFO
spring.application.name=taskmanager